-- Add tables
CREATE TABLE  "AGENTS" 
   (	
    "AGENT_CODE" CHAR(6) NOT NULL PRIMARY KEY, 
	"AGENT_NAME" CHAR(40), 
	"WORKING_AREA" CHAR(35), 
	"COMMISSION" NUMBER(10,2), 
	"PHONE_NO" CHAR(15), 
	"COUNTRY" VARCHAR2(25) 
	 );

-- Add rows
INSERT INTO AGENTS VALUES ('A007', 'Ramasundar', 'Bangalore', '0.15', '077-25814763', '');
INSERT INTO AGENTS VALUES ('A003', 'Alex ', 'London', '0.13', '075-12458969', '');
INSERT INTO AGENTS VALUES ('A008', 'Alford', 'New York', '0.12', '044-25874365', '');
INSERT INTO AGENTS VALUES ('A011', 'Ravi Kumar', 'Bangalore', '0.15', '077-45625874', '');
INSERT INTO AGENTS VALUES ('A010', 'Santakumar', 'Chennai', '0.14', '007-22388644', '');
INSERT INTO AGENTS VALUES ('A012', 'Lucida', 'San Jose', '0.12', '044-52981425', '');
INSERT INTO AGENTS VALUES ('A005', 'Anderson', 'Brisban', '0.13', '045-21447739', '');
INSERT INTO AGENTS VALUES ('A001', 'Subbarao', 'Bangalore', '0.14', '077-12346674', '');
INSERT INTO AGENTS VALUES ('A002', 'Mukesh', 'Mumbai', '0.11', '029-12358964', '');
INSERT INTO AGENTS VALUES ('A006', 'McDen', 'London', '0.15', '078-22255588', '');
INSERT INTO AGENTS VALUES ('A004', 'Ivan', 'Torento', '0.15', '008-22544166', '');
INSERT INTO AGENTS VALUES ('A009', 'Benjamin', 'Hampshair', '0.11', '008-22536178', '');
INSERT INTO AGENTS VALUES ('A015', 'John', 'London', '0.14', '034-23454344','');

--print table
SELECT * FROM AGENTS;

--count rows
SELECT COUNT(AGENT_NAME) FROM AGENTS;

-- min max querys
SELECT MAX(COMMISSION) FROM AGENTS;
SELECT MIN(COMMISSION) FROM AGENTS;

-- create group with avg
SELECT WORKING_AREA , AVG(COMMISSION) FROM AGENTS GROUP BY WORKING_AREA;

-- print avg 
SELECT AVG(COMMISSION) FROM AGENTS;

-- print acending order with agent code
SELECT * FROM AGENTS ORDER BY AGENT_CODE;

-- Find agents with commission above average
SELECT AGENT_NAME, COMMISSION 
FROM AGENTS 
WHERE COMMISSION > (SELECT AVG(COMMISSION) FROM AGENTS);

-- Count agents per working area
SELECT WORKING_AREA, COUNT(*) as A_count 
FROM AGENTS 
GROUP BY WORKING_AREA 
ORDER BY A_count DESC;

-- Find top 3 highest commission agents
SELECT AGENT_NAME, WORKING_AREA, COMMISSION 
FROM AGENTS 
ORDER BY COMMISSION DESC 
LIMIT 3;

-- Agents in Bangalore or London
SELECT AGENT_NAME, WORKING_AREA, COMMISSION 
FROM AGENTS 
WHERE WORKING_AREA IN ('Bangalore', 'London');

-- Working areas with average commission above 0.13
SELECT WORKING_AREA, AVG(COMMISSION) as A_commission 
FROM AGENTS 
GROUP BY WORKING_AREA 
HAVING AVG(COMMISSION) > 0.13;
